# .circleci/config.yml
defaults: &defaults
  docker:
    - image: python:3.7-alpine
  working_directory: ~/project
  
version: 2.1
jobs:
    build:
      <<: *defaults
      steps:
        - checkout  # checkout source code to working directory
        - run:
            command: |
              python -m venv env
              source env/bin/activate
              python -m pip install --upgrade setuptools
              python -m pip install wheel pytest pytest-cov
              python setup.py install
              pycr -h
              pytest .
        - save_cache:
             key: "py-packages"
             paths: 
                - /usr/local/lib/python3.7/site-packages
    test:          
      <<: *defaults
      steps:
        - checkout  # checkout source code to working directory
        - restore_cache:
             keys:
               - "py-packages"
        - run:
            command: |
              pwd 
              ls
              source env/bin/activate
              pycr -h
              pytest .
workflows:
  integration:
    jobs:
      - build
      - test:
          requires:
              - build
