version: 2.1
jobs:
  build_test:
      docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout  # checkout source code to working directory
      - run:
          command: |
            python -m pip install git+https://github.com/pkmklong/pycr.git
            python -m pip install pytest
            pytest
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - build_test
