version: 2.1
jobs:
    build:
      docker:
      - image: circleci/python:3.6.4
      steps:
        - checkout  # checkout source code to working directory
        - run:
            command: |
              python -m pip install virtualenv
              python -m venv env
              . env/bin/activate
              python setup.py
workflows:
  integration:
    jobs:
      - build
