# .circleci/config.yml
defaults: &defaults
  docker:
    - image: circleci/python:3.6.4
  working_directory: ~/project
  
version: 2.1
jobs:
    build:
      <<: *defaults
      steps:
        - checkout  # checkout source code to working directory
        - run:
            command: |
              python -m venv env
              source env/bin/activate
              python -m pip install --upgrade setuptools
              python -m pip install wheel
              python setup.py install
        - save_cache:
             key: "py-packages"
             paths: 
                - /home/circleci/project/env/lib/python3.6/site-packages
    test:          
      <<: *defaults
      steps:
        - checkout  # checkout source code to working directory
        - restore_cache:
             keys:
               - "py-packages"
        - run:
            command: |
              sudo python -m pip install pytest pytest-cov
              pycr -h
              pytest .
workflows:
  integration:
    jobs:
      - build
      - test:
          requires:
              - build
