# .circleci/config.yml
defaults: &defaults
  docker:
    - image: circleci/python:3.6.4
  working_directory: ~/project
  
version: 2.1
jobs:
    build:
      <<: *defaults
      steps:
        - checkout  # checkout source code to working directory
        - run:
            command: |
              chown -R $USER:$USER /usr/local/lib/python3.6/site-packages/
              python -m pip install --user --upgrade setuptools
              python -m pip install --user wheel pytest pytest-cov
              python setup.py install
              pycr -h
              pytest .
        - save_cache:
             key: "py-packages"
             paths: 
                - /usr/local/lib/python3.6/site-packages/
    test:          
      <<: *defaults
      steps:
        - checkout  # checkout source code to working directory
        - restore_cache:
             keys:
               - "py-packages"
        - run:
            command: |
              chown -R $USER:$USER /usr/local/lib/python3.6/site-packages/
              python -m pip install --user pytest pytest-cov
              pytest .
workflows:
  integration:
    jobs:
      - build
      - test:
          requires:
              - build
