version: 2.1
jobs:
    build:
      docker:
      - image: circleci/python:3.6.4
      steps:
        - checkout  # checkout source code to working directory
        - run:
            command: |
              python -m venv env
              source env/bin/activate
              python -m pip install --upgrade setuptools
              python -m pip install wheel
              python setup.py install
              pycr -h
workflows:
  integration:
    jobs:
      - build
